development:
  stripe:
    premium_plan_id: premium-monthly
    publishable_key: pk_test_iodjRiA9OzTNpXpsiIKw07wm00DXI6uf7H
    secret_key: sk_test_ujWZKkuGgPqUGYecr1uwQCOr007CVZfgaV

test: &development

